handle listing role assignment failures (#200)
In some situations, Azure responds with failures that are unrelated to our request.  One such failure is:

```
Error: unable to list active role assignments
Caused by:
request failed: status: 400 Bad Request Object {
    "error": Object {
        "code": String("ApiVersionNotRegistered"),
        "message": String("The ApiVersion '2024-06-01-Preview' is not registered for ResourceType 'Microsoft.CognitiveServices/accounts'. Valid Api Versions are:  '2016-02-01-preview' '2017-04-18' '2021-04-30' '2021-10-01' '2022-03-01' '2022-07-01' '2099-01-01' '2022-10-01' '2022-12-01' '2023-05-01' '2023-06-01-preview' '2023-10-01-preview' '2024-04-01-preview' '2024-06-01-preview'."),
    },
}
```

In practice, these failures are intermittent.

Instead of stopping, print a warning and continue.